export   { default as downIcon } from "./icon-down.svg"
export   { default as upIcon } from "./icon-up.svg"
export   { default as facebook } from "./icon-facebook.svg"
export   { default as insta } from "./icon-instagram.svg"
export   { default as twitter } from "./icon-twitter.svg"
export   { default as youtube } from "./icon-youtube.svg"